var mode = process.argv.slice(2)[0];
var jsonFile = require("../docs/lib-" + mode + "/documentation.json");

var output =
  "## Documentation Coverage for: ngx-dynamic-json-form-" +
  mode +
  ": " +
  jsonFile.coverage.count +
  "%\n\n";

output += "This Report is autogenerated and shows the Documentation coverage for the lib.\n\n";
output += "### Included files:\n\n";
output +=
  '<div className="scroll-container"><table width="100%"><thead><tr><th align="left">File</th><th align="left">Coverage</th></tr></thead><tbody>';

jsonFile.coverage.files.forEach(function (data) {
  output +=
    "<tr><td>" +
    data.filePath.replaceAll("\\", "/").replace("projects/lib-" + mode + "/src/lib/", "") +
    "</td><td>" +
    data.coveragePercent +
    "%</td></tr>\n";
});

output += "</tbody></table></div>";

try {
  require("fs").writeFileSync(
    "./projects/lib-" + mode + "/COVERAGE-DOCS.md",
    output,
    "utf-8",
    "w+"
  );

  console.log("\x1b[32m%s\x1b[0m", "info", "=> coverage file for " + mode + " was generated");
} catch (error) {
  console.log("Error: Cannot write file");
  throw error;
}
